networks:
  main:
  front-back:

services:
  bankdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=PaSSword12345
        - MSSQL_PID=Developer
    
    networks:
        - main
    volumes:
        - database:/var/opt/mssql
  bank:
    container_name: bank-back
    build:
        context: .
        dockerfile: bank/Dockerfile
    ports:
        - 8080:8081
    depends_on:
        - bankdb
    environment:
        - DB_HOST=bankdb
        - DB_NAME=bank
        - DB_SA_PASSWORD=PaSSword12345
    networks:
        - main
        - front-back 
  front:
    container_name: bank-front
    build:
      context: ../frontend-bank
      dockerfile: ../frontend-bank/Dockerfile
    ports:
        - 5173:80
    networks:
        - front-back
volumes:
  database: